name: Test
on:
  pull_request:
    paths: ['go/**/*.go']
permissions:
  pull_requests: write
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Read .go-version
        id: read_version
        run: |
          VERSION=$(cat .go-version)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr comment "${GITHUB_HEAD_REF}" --body "Go Version:${VERSION}"
      
      - uses: actions/setup-go@v5
        with:
          go-version-file: .go-version
      - run: go test go/excellent/*.go
