name: Manual
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options:
          - debug
          - staging
          - release
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.env }}"
