name: Comment
on: push
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: echo "${GITHUB_HEAD_REF}"
