name: Log group
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    env:
      PASSWORD: SupeorSecretValue
    steps:
      - run: |
          echo "::group::SHow environment variables"
          echo "This is debug log."
          echo "endgroup"
      - run: echo "::add-mask::${PASSWORD}"
      - run: echo "${PASSWORD}"
