name: Literals
on:
  push:
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep 'LLITERAL_'
        env:
          LITERAL_NULL: ${{ null }}
          LITERAL_BOOLEAN: ${{ true }}
          LITERAL_NUMBER: ${{ 1234 }}
          LITERAL_STRING: ${{ 'HELLO' }}
          LITERAL_OMIT_STRING: World
